<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KelasKuisionerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // questionaires
        $kelasKuisioners = array(
            array('id' => '1','kelas_id' => '25','bank_kuisioner_id' => '1'),
            array('id' => '2','kelas_id' => '25','bank_kuisioner_id' => '2'),
            array('id' => '3','kelas_id' => '25','bank_kuisioner_id' => '3'),
            array('id' => '4','kelas_id' => '25','bank_kuisioner_id' => '4'),
            array('id' => '5','kelas_id' => '25','bank_kuisioner_id' => '5'),
            array('id' => '6','kelas_id' => '25','bank_kuisioner_id' => '6'),
            array('id' => '7','kelas_id' => '25','bank_kuisioner_id' => '7'),
            array('id' => '8','kelas_id' => '25','bank_kuisioner_id' => '8'),
            array('id' => '9','kelas_id' => '25','bank_kuisioner_id' => '9'),
            array('id' => '10','kelas_id' => '25','bank_kuisioner_id' => '10'),
            array('id' => '11','kelas_id' => '25','bank_kuisioner_id' => '20'),
            array('id' => '12','kelas_id' => '25','bank_kuisioner_id' => '21'),
            array('id' => '13','kelas_id' => '25','bank_kuisioner_id' => '22'),
            array('id' => '14','kelas_id' => '25','bank_kuisioner_id' => '23'),
            array('id' => '15','kelas_id' => '25','bank_kuisioner_id' => '24'),
            array('id' => '16','kelas_id' => '25','bank_kuisioner_id' => '25'),
            array('id' => '17','kelas_id' => '25','bank_kuisioner_id' => '26'),
            array('id' => '18','kelas_id' => '25','bank_kuisioner_id' => '27'),
            array('id' => '19','kelas_id' => '25','bank_kuisioner_id' => '11'),
            array('id' => '20','kelas_id' => '25','bank_kuisioner_id' => '12'),
            array('id' => '21','kelas_id' => '25','bank_kuisioner_id' => '13'),
            array('id' => '22','kelas_id' => '25','bank_kuisioner_id' => '14'),
            array('id' => '23','kelas_id' => '25','bank_kuisioner_id' => '15'),
            array('id' => '24','kelas_id' => '25','bank_kuisioner_id' => '16'),
            array('id' => '25','kelas_id' => '25','bank_kuisioner_id' => '17'),
            array('id' => '26','kelas_id' => '25','bank_kuisioner_id' => '18'),
            array('id' => '27','kelas_id' => '25','bank_kuisioner_id' => '19'),
            array('id' => '28','kelas_id' => '25','bank_kuisioner_id' => '28'),
            array('id' => '29','kelas_id' => '25','bank_kuisioner_id' => '29'),
            array('id' => '30','kelas_id' => '25','bank_kuisioner_id' => '30'),
            array('id' => '31','kelas_id' => '25','bank_kuisioner_id' => '31'),
            array('id' => '32','kelas_id' => '25','bank_kuisioner_id' => '32'),
            array('id' => '33','kelas_id' => '25','bank_kuisioner_id' => '33'),
            array('id' => '34','kelas_id' => '25','bank_kuisioner_id' => '34'),
            array('id' => '35','kelas_id' => '25','bank_kuisioner_id' => '35'),
            array('id' => '36','kelas_id' => '25','bank_kuisioner_id' => '36'),
            array('id' => '37','kelas_id' => '25','bank_kuisioner_id' => '37'),
            array('id' => '38','kelas_id' => '25','bank_kuisioner_id' => '38'),
            array('id' => '39','kelas_id' => '25','bank_kuisioner_id' => '39'),
            array('id' => '40','kelas_id' => '25','bank_kuisioner_id' => '40'),
            array('id' => '41','kelas_id' => '25','bank_kuisioner_id' => '41'),
            array('id' => '42','kelas_id' => '25','bank_kuisioner_id' => '42'),
            array('id' => '43','kelas_id' => '25','bank_kuisioner_id' => '43'),
            array('id' => '44','kelas_id' => '25','bank_kuisioner_id' => '44'),
            array('id' => '45','kelas_id' => '25','bank_kuisioner_id' => '45'),
            array('id' => '46','kelas_id' => '25','bank_kuisioner_id' => '46'),
            array('id' => '47','kelas_id' => '25','bank_kuisioner_id' => '47'),
            array('id' => '48','kelas_id' => '25','bank_kuisioner_id' => '48'),
            array('id' => '49','kelas_id' => '25','bank_kuisioner_id' => '49'),
            array('id' => '50','kelas_id' => '25','bank_kuisioner_id' => '50'),
            array('id' => '51','kelas_id' => '25','bank_kuisioner_id' => '51'),
            array('id' => '52','kelas_id' => '25','bank_kuisioner_id' => '52'),
            array('id' => '53','kelas_id' => '25','bank_kuisioner_id' => '53'),
            array('id' => '54','kelas_id' => '25','bank_kuisioner_id' => '54'),
            array('id' => '55','kelas_id' => '25','bank_kuisioner_id' => '55'),
            array('id' => '56','kelas_id' => '25','bank_kuisioner_id' => '56'),
            array('id' => '57','kelas_id' => '25','bank_kuisioner_id' => '57'),
            array('id' => '58','kelas_id' => '25','bank_kuisioner_id' => '58'),
            array('id' => '59','kelas_id' => '25','bank_kuisioner_id' => '59'),
            array('id' => '60','kelas_id' => '25','bank_kuisioner_id' => '60'),
            array('id' => '61','kelas_id' => '25','bank_kuisioner_id' => '61'),
            array('id' => '62','kelas_id' => '25','bank_kuisioner_id' => '62'),
            array('id' => '63','kelas_id' => '25','bank_kuisioner_id' => '63'),
            array('id' => '64','kelas_id' => '18','bank_kuisioner_id' => '1'),
            array('id' => '65','kelas_id' => '18','bank_kuisioner_id' => '2'),
            array('id' => '66','kelas_id' => '18','bank_kuisioner_id' => '3'),
            array('id' => '67','kelas_id' => '18','bank_kuisioner_id' => '4'),
            array('id' => '68','kelas_id' => '18','bank_kuisioner_id' => '5'),
            array('id' => '69','kelas_id' => '18','bank_kuisioner_id' => '6'),
            array('id' => '70','kelas_id' => '18','bank_kuisioner_id' => '7'),
            array('id' => '71','kelas_id' => '18','bank_kuisioner_id' => '8'),
            array('id' => '72','kelas_id' => '18','bank_kuisioner_id' => '9'),
            array('id' => '73','kelas_id' => '18','bank_kuisioner_id' => '10'),
            array('id' => '74','kelas_id' => '18','bank_kuisioner_id' => '11'),
            array('id' => '75','kelas_id' => '18','bank_kuisioner_id' => '12'),
            array('id' => '76','kelas_id' => '18','bank_kuisioner_id' => '13'),
            array('id' => '77','kelas_id' => '18','bank_kuisioner_id' => '14'),
            array('id' => '78','kelas_id' => '18','bank_kuisioner_id' => '15'),
            array('id' => '79','kelas_id' => '18','bank_kuisioner_id' => '16'),
            array('id' => '80','kelas_id' => '18','bank_kuisioner_id' => '17'),
            array('id' => '81','kelas_id' => '18','bank_kuisioner_id' => '18'),
            array('id' => '82','kelas_id' => '18','bank_kuisioner_id' => '19'),
            array('id' => '83','kelas_id' => '18','bank_kuisioner_id' => '20'),
            array('id' => '84','kelas_id' => '18','bank_kuisioner_id' => '21'),
            array('id' => '85','kelas_id' => '18','bank_kuisioner_id' => '22'),
            array('id' => '86','kelas_id' => '18','bank_kuisioner_id' => '23'),
            array('id' => '87','kelas_id' => '18','bank_kuisioner_id' => '24'),
            array('id' => '88','kelas_id' => '18','bank_kuisioner_id' => '25'),
            array('id' => '89','kelas_id' => '18','bank_kuisioner_id' => '26'),
            array('id' => '90','kelas_id' => '18','bank_kuisioner_id' => '27'),
            array('id' => '91','kelas_id' => '18','bank_kuisioner_id' => '28'),
            array('id' => '92','kelas_id' => '18','bank_kuisioner_id' => '29'),
            array('id' => '93','kelas_id' => '18','bank_kuisioner_id' => '30'),
            array('id' => '94','kelas_id' => '18','bank_kuisioner_id' => '31'),
            array('id' => '95','kelas_id' => '18','bank_kuisioner_id' => '32'),
            array('id' => '96','kelas_id' => '18','bank_kuisioner_id' => '33'),
            array('id' => '97','kelas_id' => '18','bank_kuisioner_id' => '34'),
            array('id' => '98','kelas_id' => '18','bank_kuisioner_id' => '35'),
            array('id' => '99','kelas_id' => '18','bank_kuisioner_id' => '45'),
            array('id' => '100','kelas_id' => '18','bank_kuisioner_id' => '46'),
            array('id' => '101','kelas_id' => '18','bank_kuisioner_id' => '47'),
            array('id' => '102','kelas_id' => '18','bank_kuisioner_id' => '48'),
            array('id' => '103','kelas_id' => '18','bank_kuisioner_id' => '49'),
            array('id' => '104','kelas_id' => '18','bank_kuisioner_id' => '50'),
            array('id' => '105','kelas_id' => '18','bank_kuisioner_id' => '51'),
            array('id' => '106','kelas_id' => '18','bank_kuisioner_id' => '52'),
            array('id' => '107','kelas_id' => '18','bank_kuisioner_id' => '53'),
            array('id' => '108','kelas_id' => '18','bank_kuisioner_id' => '36'),
            array('id' => '109','kelas_id' => '18','bank_kuisioner_id' => '37'),
            array('id' => '110','kelas_id' => '18','bank_kuisioner_id' => '38'),
            array('id' => '111','kelas_id' => '18','bank_kuisioner_id' => '39'),
            array('id' => '112','kelas_id' => '18','bank_kuisioner_id' => '40'),
            array('id' => '113','kelas_id' => '18','bank_kuisioner_id' => '41'),
            array('id' => '114','kelas_id' => '18','bank_kuisioner_id' => '42'),
            array('id' => '115','kelas_id' => '18','bank_kuisioner_id' => '43'),
            array('id' => '116','kelas_id' => '18','bank_kuisioner_id' => '44'),
            array('id' => '117','kelas_id' => '18','bank_kuisioner_id' => '54'),
            array('id' => '118','kelas_id' => '18','bank_kuisioner_id' => '55'),
            array('id' => '119','kelas_id' => '18','bank_kuisioner_id' => '56'),
            array('id' => '120','kelas_id' => '18','bank_kuisioner_id' => '57'),
            array('id' => '121','kelas_id' => '18','bank_kuisioner_id' => '58'),
            array('id' => '122','kelas_id' => '18','bank_kuisioner_id' => '59'),
            array('id' => '123','kelas_id' => '18','bank_kuisioner_id' => '60'),
            array('id' => '124','kelas_id' => '18','bank_kuisioner_id' => '61'),
            array('id' => '125','kelas_id' => '18','bank_kuisioner_id' => '62'),
            array('id' => '126','kelas_id' => '18','bank_kuisioner_id' => '63'),
            // array('id' => '127','kelas_id' => '27','bank_kuisioner_id' => '11'),
            // array('id' => '128','kelas_id' => '27','bank_kuisioner_id' => '12'),
            // array('id' => '129','kelas_id' => '27','bank_kuisioner_id' => '13'),
            // array('id' => '130','kelas_id' => '27','bank_kuisioner_id' => '14'),
            // array('id' => '131','kelas_id' => '27','bank_kuisioner_id' => '15'),
            // array('id' => '132','kelas_id' => '27','bank_kuisioner_id' => '16'),
            // array('id' => '133','kelas_id' => '27','bank_kuisioner_id' => '17'),
            // array('id' => '134','kelas_id' => '27','bank_kuisioner_id' => '18'),
            // array('id' => '135','kelas_id' => '27','bank_kuisioner_id' => '19'),
            // array('id' => '136','kelas_id' => '28','bank_kuisioner_id' => '1'),
            // array('id' => '137','kelas_id' => '28','bank_kuisioner_id' => '2'),
            // array('id' => '138','kelas_id' => '28','bank_kuisioner_id' => '3'),
            // array('id' => '139','kelas_id' => '28','bank_kuisioner_id' => '4'),
            // array('id' => '140','kelas_id' => '28','bank_kuisioner_id' => '5'),
            // array('id' => '141','kelas_id' => '28','bank_kuisioner_id' => '6'),
            // array('id' => '142','kelas_id' => '28','bank_kuisioner_id' => '7'),
            // array('id' => '143','kelas_id' => '28','bank_kuisioner_id' => '8'),
            // array('id' => '144','kelas_id' => '28','bank_kuisioner_id' => '9'),
            // array('id' => '145','kelas_id' => '28','bank_kuisioner_id' => '10'),
            // array('id' => '146','kelas_id' => '28','bank_kuisioner_id' => '11'),
            // array('id' => '147','kelas_id' => '28','bank_kuisioner_id' => '12'),
            // array('id' => '148','kelas_id' => '28','bank_kuisioner_id' => '13'),
            // array('id' => '149','kelas_id' => '28','bank_kuisioner_id' => '14'),
            // array('id' => '150','kelas_id' => '28','bank_kuisioner_id' => '15'),
            // array('id' => '151','kelas_id' => '28','bank_kuisioner_id' => '16'),
            // array('id' => '152','kelas_id' => '28','bank_kuisioner_id' => '17'),
            // array('id' => '153','kelas_id' => '28','bank_kuisioner_id' => '18'),
            // array('id' => '154','kelas_id' => '28','bank_kuisioner_id' => '19'),
            // array('id' => '155','kelas_id' => '28','bank_kuisioner_id' => '20'),
            // array('id' => '156','kelas_id' => '28','bank_kuisioner_id' => '21'),
            // array('id' => '157','kelas_id' => '28','bank_kuisioner_id' => '22'),
            // array('id' => '158','kelas_id' => '28','bank_kuisioner_id' => '23'),
            // array('id' => '159','kelas_id' => '28','bank_kuisioner_id' => '24'),
            // array('id' => '160','kelas_id' => '28','bank_kuisioner_id' => '25'),
            // array('id' => '161','kelas_id' => '28','bank_kuisioner_id' => '26'),
            // array('id' => '162','kelas_id' => '28','bank_kuisioner_id' => '27'),
            // array('id' => '163','kelas_id' => '28','bank_kuisioner_id' => '28'),
            // array('id' => '164','kelas_id' => '28','bank_kuisioner_id' => '29'),
            // array('id' => '165','kelas_id' => '28','bank_kuisioner_id' => '30'),
            // array('id' => '166','kelas_id' => '28','bank_kuisioner_id' => '31'),
            // array('id' => '167','kelas_id' => '28','bank_kuisioner_id' => '32'),
            // array('id' => '168','kelas_id' => '28','bank_kuisioner_id' => '33'),
            // array('id' => '169','kelas_id' => '28','bank_kuisioner_id' => '34'),
            // array('id' => '170','kelas_id' => '28','bank_kuisioner_id' => '35'),
            // array('id' => '171','kelas_id' => '28','bank_kuisioner_id' => '36'),
            // array('id' => '172','kelas_id' => '28','bank_kuisioner_id' => '37'),
            // array('id' => '173','kelas_id' => '28','bank_kuisioner_id' => '38'),
            // array('id' => '174','kelas_id' => '28','bank_kuisioner_id' => '39'),
            // array('id' => '175','kelas_id' => '28','bank_kuisioner_id' => '40'),
            // array('id' => '176','kelas_id' => '28','bank_kuisioner_id' => '41'),
            // array('id' => '177','kelas_id' => '28','bank_kuisioner_id' => '42'),
            // array('id' => '178','kelas_id' => '28','bank_kuisioner_id' => '43'),
            // array('id' => '179','kelas_id' => '28','bank_kuisioner_id' => '44'),
            // array('id' => '180','kelas_id' => '28','bank_kuisioner_id' => '45'),
            // array('id' => '181','kelas_id' => '28','bank_kuisioner_id' => '46'),
            // array('id' => '182','kelas_id' => '28','bank_kuisioner_id' => '47'),
            // array('id' => '183','kelas_id' => '28','bank_kuisioner_id' => '48'),
            // array('id' => '184','kelas_id' => '28','bank_kuisioner_id' => '49'),
            // array('id' => '185','kelas_id' => '28','bank_kuisioner_id' => '50'),
            // array('id' => '186','kelas_id' => '28','bank_kuisioner_id' => '51'),
            // array('id' => '187','kelas_id' => '28','bank_kuisioner_id' => '52'),
            // array('id' => '188','kelas_id' => '28','bank_kuisioner_id' => '53'),
            // array('id' => '189','kelas_id' => '28','bank_kuisioner_id' => '54'),
            // array('id' => '190','kelas_id' => '28','bank_kuisioner_id' => '55'),
            // array('id' => '191','kelas_id' => '28','bank_kuisioner_id' => '56'),
            // array('id' => '192','kelas_id' => '28','bank_kuisioner_id' => '57'),
            // array('id' => '193','kelas_id' => '28','bank_kuisioner_id' => '58'),
            // array('id' => '194','kelas_id' => '28','bank_kuisioner_id' => '59'),
            // array('id' => '195','kelas_id' => '28','bank_kuisioner_id' => '60'),
            // array('id' => '196','kelas_id' => '28','bank_kuisioner_id' => '61'),
            // array('id' => '197','kelas_id' => '28','bank_kuisioner_id' => '62'),
            // array('id' => '198','kelas_id' => '28','bank_kuisioner_id' => '63'),
            // array('id' => '218','kelas_id' => '29','bank_kuisioner_id' => '28'),
            // array('id' => '220','kelas_id' => '29','bank_kuisioner_id' => '30'),
            // array('id' => '221','kelas_id' => '29','bank_kuisioner_id' => '31'),
            // array('id' => '222','kelas_id' => '29','bank_kuisioner_id' => '32'),
            // array('id' => '223','kelas_id' => '29','bank_kuisioner_id' => '33'),
            // array('id' => '224','kelas_id' => '29','bank_kuisioner_id' => '34'),
            // array('id' => '225','kelas_id' => '29','bank_kuisioner_id' => '35'),
            // array('id' => '226','kelas_id' => '29','bank_kuisioner_id' => '1'),
            // array('id' => '227','kelas_id' => '29','bank_kuisioner_id' => '2'),
            // array('id' => '228','kelas_id' => '29','bank_kuisioner_id' => '3'),
            // array('id' => '229','kelas_id' => '29','bank_kuisioner_id' => '4'),
            // array('id' => '230','kelas_id' => '29','bank_kuisioner_id' => '5'),
            // array('id' => '231','kelas_id' => '29','bank_kuisioner_id' => '6'),
            // array('id' => '232','kelas_id' => '29','bank_kuisioner_id' => '7'),
            // array('id' => '233','kelas_id' => '29','bank_kuisioner_id' => '8'),
            // array('id' => '234','kelas_id' => '29','bank_kuisioner_id' => '9'),
            // array('id' => '235','kelas_id' => '29','bank_kuisioner_id' => '10'),
            array('id' => '236','kelas_id' => '31','bank_kuisioner_id' => '1'),
            array('id' => '237','kelas_id' => '31','bank_kuisioner_id' => '2'),
            array('id' => '238','kelas_id' => '31','bank_kuisioner_id' => '3'),
            array('id' => '239','kelas_id' => '31','bank_kuisioner_id' => '4'),
            array('id' => '240','kelas_id' => '31','bank_kuisioner_id' => '5'),
            array('id' => '241','kelas_id' => '31','bank_kuisioner_id' => '6'),
            array('id' => '242','kelas_id' => '31','bank_kuisioner_id' => '7'),
            array('id' => '243','kelas_id' => '31','bank_kuisioner_id' => '8'),
            array('id' => '244','kelas_id' => '31','bank_kuisioner_id' => '9'),
            array('id' => '245','kelas_id' => '31','bank_kuisioner_id' => '10'),
            array('id' => '246','kelas_id' => '31','bank_kuisioner_id' => '11'),
            array('id' => '247','kelas_id' => '31','bank_kuisioner_id' => '12'),
            array('id' => '248','kelas_id' => '31','bank_kuisioner_id' => '13'),
            array('id' => '249','kelas_id' => '31','bank_kuisioner_id' => '14'),
            array('id' => '250','kelas_id' => '31','bank_kuisioner_id' => '15'),
            array('id' => '251','kelas_id' => '31','bank_kuisioner_id' => '16'),
            array('id' => '252','kelas_id' => '31','bank_kuisioner_id' => '17'),
            array('id' => '253','kelas_id' => '31','bank_kuisioner_id' => '18'),
            array('id' => '254','kelas_id' => '31','bank_kuisioner_id' => '19'),
            array('id' => '255','kelas_id' => '31','bank_kuisioner_id' => '20'),
            array('id' => '256','kelas_id' => '31','bank_kuisioner_id' => '21'),
            array('id' => '257','kelas_id' => '31','bank_kuisioner_id' => '22'),
            array('id' => '258','kelas_id' => '31','bank_kuisioner_id' => '23'),
            array('id' => '259','kelas_id' => '31','bank_kuisioner_id' => '24'),
            array('id' => '260','kelas_id' => '31','bank_kuisioner_id' => '25'),
            array('id' => '261','kelas_id' => '31','bank_kuisioner_id' => '26'),
            array('id' => '262','kelas_id' => '31','bank_kuisioner_id' => '27'),
            array('id' => '263','kelas_id' => '31','bank_kuisioner_id' => '28'),
            array('id' => '264','kelas_id' => '31','bank_kuisioner_id' => '29'),
            array('id' => '265','kelas_id' => '31','bank_kuisioner_id' => '30'),
            array('id' => '266','kelas_id' => '31','bank_kuisioner_id' => '31'),
            array('id' => '267','kelas_id' => '31','bank_kuisioner_id' => '32'),
            array('id' => '268','kelas_id' => '31','bank_kuisioner_id' => '33'),
            array('id' => '269','kelas_id' => '31','bank_kuisioner_id' => '34'),
            array('id' => '270','kelas_id' => '31','bank_kuisioner_id' => '35'),
            array('id' => '271','kelas_id' => '31','bank_kuisioner_id' => '36'),
            array('id' => '272','kelas_id' => '31','bank_kuisioner_id' => '37'),
            array('id' => '273','kelas_id' => '31','bank_kuisioner_id' => '38'),
            array('id' => '274','kelas_id' => '31','bank_kuisioner_id' => '39'),
            array('id' => '275','kelas_id' => '31','bank_kuisioner_id' => '40'),
            array('id' => '276','kelas_id' => '31','bank_kuisioner_id' => '41'),
            array('id' => '277','kelas_id' => '31','bank_kuisioner_id' => '42'),
            array('id' => '278','kelas_id' => '31','bank_kuisioner_id' => '43'),
            array('id' => '279','kelas_id' => '31','bank_kuisioner_id' => '44'),
            array('id' => '280','kelas_id' => '31','bank_kuisioner_id' => '45'),
            array('id' => '281','kelas_id' => '31','bank_kuisioner_id' => '46'),
            array('id' => '282','kelas_id' => '31','bank_kuisioner_id' => '47'),
            array('id' => '283','kelas_id' => '31','bank_kuisioner_id' => '48'),
            array('id' => '284','kelas_id' => '31','bank_kuisioner_id' => '49'),
            array('id' => '285','kelas_id' => '31','bank_kuisioner_id' => '50'),
            array('id' => '286','kelas_id' => '31','bank_kuisioner_id' => '51'),
            array('id' => '287','kelas_id' => '31','bank_kuisioner_id' => '52'),
            array('id' => '288','kelas_id' => '31','bank_kuisioner_id' => '53'),
            array('id' => '289','kelas_id' => '31','bank_kuisioner_id' => '54'),
            array('id' => '290','kelas_id' => '31','bank_kuisioner_id' => '55'),
            array('id' => '291','kelas_id' => '31','bank_kuisioner_id' => '56'),
            array('id' => '292','kelas_id' => '31','bank_kuisioner_id' => '57'),
            array('id' => '293','kelas_id' => '31','bank_kuisioner_id' => '58'),
            array('id' => '294','kelas_id' => '31','bank_kuisioner_id' => '59'),
            array('id' => '295','kelas_id' => '31','bank_kuisioner_id' => '60'),
            array('id' => '296','kelas_id' => '31','bank_kuisioner_id' => '61'),
            array('id' => '297','kelas_id' => '31','bank_kuisioner_id' => '62'),
            array('id' => '298','kelas_id' => '31','bank_kuisioner_id' => '63'),
            array('id' => '299','kelas_id' => '32','bank_kuisioner_id' => '64'),
            array('id' => '300','kelas_id' => '32','bank_kuisioner_id' => '65'),
            array('id' => '301','kelas_id' => '32','bank_kuisioner_id' => '66'),
            array('id' => '302','kelas_id' => '32','bank_kuisioner_id' => '67'),
            array('id' => '303','kelas_id' => '32','bank_kuisioner_id' => '68'),
            array('id' => '304','kelas_id' => '32','bank_kuisioner_id' => '69'),
            array('id' => '305','kelas_id' => '32','bank_kuisioner_id' => '70'),
            array('id' => '306','kelas_id' => '32','bank_kuisioner_id' => '71'),
            array('id' => '307','kelas_id' => '32','bank_kuisioner_id' => '72'),
            array('id' => '308','kelas_id' => '32','bank_kuisioner_id' => '73'),
            array('id' => '309','kelas_id' => '32','bank_kuisioner_id' => '74'),
            array('id' => '310','kelas_id' => '32','bank_kuisioner_id' => '75'),
            array('id' => '311','kelas_id' => '32','bank_kuisioner_id' => '76'),
            array('id' => '312','kelas_id' => '32','bank_kuisioner_id' => '77'),
            array('id' => '313','kelas_id' => '32','bank_kuisioner_id' => '78'),
            array('id' => '314','kelas_id' => '32','bank_kuisioner_id' => '79'),
            array('id' => '315','kelas_id' => '32','bank_kuisioner_id' => '80'),
            array('id' => '316','kelas_id' => '32','bank_kuisioner_id' => '81'),
            array('id' => '317','kelas_id' => '32','bank_kuisioner_id' => '82'),
            array('id' => '318','kelas_id' => '32','bank_kuisioner_id' => '83'),
            array('id' => '319','kelas_id' => '32','bank_kuisioner_id' => '84'),
            array('id' => '320','kelas_id' => '32','bank_kuisioner_id' => '85'),
            array('id' => '321','kelas_id' => '32','bank_kuisioner_id' => '87'),
            array('id' => '322','kelas_id' => '32','bank_kuisioner_id' => '88'),
            array('id' => '323','kelas_id' => '32','bank_kuisioner_id' => '89'),
            array('id' => '324','kelas_id' => '32','bank_kuisioner_id' => '90'),
            array('id' => '325','kelas_id' => '32','bank_kuisioner_id' => '92'),
            array('id' => '326','kelas_id' => '32','bank_kuisioner_id' => '93'),
            array('id' => '327','kelas_id' => '32','bank_kuisioner_id' => '94')
        );

        foreach ($kelasKuisioners as $kelasKuisioner) {
            DB::table('kelas_kuisioner')->insert($kelasKuisioner);
        }
    }
}
